# Variables

A variable is a piece of data in your program with an associated value. They are used to store values for later use. The values of variables can change over time. You cannot do without variables when writing a program. 

To give a value to a variable, simply write :  
``` python 
variable_name = value
```


For example, to store my age, just write :  
``` python 
age = 26
```

This step is called "variable assignment", in this example we have assigned the value `26` to the variable `age`.


For your organization and to be able to find your way through your code later, it is advisable to respect some syntax rules: 
- the name of the variable can only be composed of letters, upper or lower case, numbers and the underlined symbol "_".
- the variable name cannot start with a number
- Python is case sensitive, i.e. the variable `AGE` is different from the variable `age` which is different from the variable `aGe`...
- the name of the variable must be explicit with respect to its role. That is, don't call your variables `a`, `b`, `c` and `d`. When you need to reuse your code, you won't know which variable corresponds to what. 

## The type of variable

The type of the variable corresponds to the nature of the variable. The main ones used are : 
- integers (int or integer)
- decimals (float)
- strings (string or str)
- Booleans


ATTENTION
In order for the program to understand that you want to use a character string, you must remember to surround it with inverted commas (double " or single ' ).

## Operations

The four basic arithmetic operations are performed in a simple way using the symbols +-*/. on integer and decimal types. The use of parentheses allows you to manage the priorities of the operations.  
The following table summarises the basic operations.
<img src="images/1_0_OperateursPython.jpg" alt="drawing" /> 

## Operations on strings

Addition and multiplication can be used on strings. However, their action is not the same as for numerical variables.  
Addition concatenates the two strings. That is, it assembles the two strings in sequence.  Ex:  
``` python
chaine1 = "salut "
chaine2 = "le monde"
print(chaine1+chaine2)
```
`>>> salut le monde`  

Multiplication between a character string and an integer duplicates the character string. Ex: 
``` python
chaine1 = "salut "
print(chaine1*3)
```
`>>>salut salut salut` 

### Exercice

Create a variable with your age, and display it. Then add 5 to this variable and display it.   
What is the new value of your variable?   
Instead of adding the integer 5, try adding the float 5. What do you notice about the result?  

# Listes

A list is a data structure that contains a series of values. These lists can be composed of elements of the same type or of different types (e.g. string and float).  
A list is declared by a series of values separated by **commas** and the entirety is surrounded by **square brackets**.  
Examples :  
```python
ac = ['dcp1', 'cellmask', '']
quantite = [100, 200, 50]
mixte = ['dcp1', 100, 'cellmask', 200, '', 50]
```

One of the advantages of a list is that you can call its elements by their positions (= index of the list). However, be careful, the first element of a list is at index 0.  
Examples : 
```python 
mixte = ['dcp1', 100, 'cellmask', 200, '', 50]
indice =     0     1          2     3       4
```
So we have our mixed list which contains 5 elements from index 0 to 4. 



Lists support the + operation for concatenation and * for duplication. Their use is the same as for strings. 

The `len(my_list)` statement is used to find out the size of the list.  

It is also possible to create lists of lists. 
Example:   
```python
rack1 = ['Sqh-GFP', 'uas Rho1RNAi', 'uas Rok']
rack2 = ['Diap', 'quas-rpr']
rack3 = ['67Gal4', 'tubGal80ts', 'uasSnail'
stock = [rack1, rack2, rack3]
print (stock)
```
`>>> [['Sqh-GFP', 'uas Rho1RNAi', 'uas Rok'], ['Diap', 'quas-rpr'], ['67Gal4', 'tubGal80ts', 'uasSnail']]`
 

It is possible to append an element to the end of the list with the `append()` method. For example, to add the line 'GC3I' to our rack1 list, we would write: `rack1.append('GC3I')`.   
You can also delete elements of a list. For example, I want to remove 'uas Rho1RNAi' from my rack1 list. Here, two methods are possible: 
- delete the element at position i. `rack1.del(1)`
- remove from the value. `rack1.remove('uas Rho1RNAi')` Be careful, in this case, if 'uas Rho1RNAi' appears several times in the list. Only the first occurrence will be removed. 

## Exercise

Create a list of days of the week with Sunday missing.   
Add Sunday. 
Delete Wednesday.

# Using scientific libraries - Numpy Scipy Pandas

## Numpy

The Numpy library allows you to perform numerical calculations. Moreover, it allows an easy management of arrays of numbers. 
This library is often used with the Pandas library, which allows the management of arrays containing different types of data (int, string, float...)

### Creating an array
As we saw earlier, to create an array we use `[]`. 
We can create an `numpy.array()` in the same way.  
Note that an array object only contains homogeneous data, i.e. of the same type.  
The array() function can create arrays of any number of dimensions. However, it quickly becomes complicated
when you exceed three dimensions. Remember that a one-dimensional array object can be considered as a vector and a two-dimensional array as a matrix. Here are some interesting attributes to describe an array object:
- .ndim returns the number of dimensions (for example, 1 for a vector and 2 for a matrix)
- .shape returns the dimensions as a tuple
- .size returns the total number of elements contained in the array.
1


In [1]:
#Importation de la librarie numpy
import numpy as np

# This is one dimension array
tableau1d = np.array([1,2,3])
# This is two dimension array
tableau2d = np.array([[1,2,3],[4,5,6]])

print(tableau1d)
print(tableau2d)

[1 2 3]
[[1 2 3]
 [4 5 6]]


###  Retrieving elements from an array
To retrieve one or more elements of an array object, you can use indices or slices, in the same way as with lists
same way as with lists:
```python
tableau1d = np.array([1,2,3,4,5,6,7,8,9,10])
print(tableau1d[1])
```
`>> 2`
```python
print(tableau1d[7:10])
```
`>> [8 9 10]`



In the case of a two-dimensional array object, you can retrieve a complete row (with index m), a complete column (with index n) or a single element. 1
``` ptyhon
tableau2d = np.array([[1,2,3],[4,5,6]])
print(tableau2d[:,0])
```
`>>[1 4]`
```python
print(tableau2d[0,:])
```
`>>[1 2 3]`
```python
print(tableau2d[0,1])
```
`>> 2`

The syntax a[m,:] returns row m-1, and a[:,n] returns column n-1. Slices are obviously also usable on a two-dimensional array.

## Pandas

The pandas module has been designed for data manipulation and analysis. It is particularly powerful for manipulating structured data in array form. To load pandas into Python's memory, we use the usual import command: `import pandas as pd`. 

## Series
The first data type provided by pandas is **series**, which corresponds to a one-dimensional vector.  
`s = pd.Series ([10, 20, 30, 40], index = ['a', 'b', 'c', 'd'])`
With pandas, each element in the data series has a label that allows you to call the elements. Thus, to call the first element of the series, we can use its index, as for a list (0 for the first element) or its label (here, "a").   
Of course, several elements can be extracted, by their indexes or their labels:
```
s[[1 ,3]]
s[["b","d"]]
```
Labels allow you to modify and add elements:
```
s["c"] = 300
s["z"] = 50
s
```

Finally, one can filter a part of the series: `s[s>30]` and even combine several selection criteria: `s[(s>20) & (s <100)]`

## Dataframes
Another particularly interesting type of object introduced by pandas are **dataframes**. These are two-dimensional arrays with labels to name the rows and columns.  

Here is how to create a dataframe with pandas from data provided as a list of rows:
```python
df = pd.DataFrame(columns =["Paris", "Lyon", "Nantes", "Pau"],
    index =[" chat", "singe", "souris"],
    data=[np.arange (10, 14),
    np.arange (20, 24),
    np.arange (30, 34)])
```

**Ligne 1.** The dataframe is created with the DataFrame() function which is given several arguments. The columns argument specifies the names of the columns, as a list.   
**Ligne 2.** The index argument defines the name of the rows, as a list.   
**Lignes 3-5.** the data argument provides the contents of the dataframe, as a list of values corresponding to rows. Thus np.arange(10, 14) which is equivalent to [10, 11, 12, 13] corresponds to the first line of the dataframe.  

### Some properties

The dimensions of a dataframe are given by the **.shape** attribute:
df.shape
Here, the df dataframe has 3 rows and 4 columns.   

The **.columns** attribute returns the names of the columns and also allows the columns of a dataframe to be renamed:
df.columns

The **.head(n)** method returns the first n rows of the dataframe (by default, n is 5):


### Selection

The selection mechanisms provided with pandas are very powerful. 

#### Selecting columns
You can select a column by its label: `df["Lyon"]`
or several columns at the same time: `df[["Lyon", "Pau"]]`.  
When selecting multiple columns, the labels of interest are collected in a list.

#### Selecting rows
To select a row, use the .loc() statement and the row label: `df.loc["monkey"]`. Again, multiple lines can be selected: `df.loc[["monkey", "cat"]]`.
Finally, you can also select lines with the .iloc statement and the line index (the first line having index 0): `df.iloc[1]`.  
You can also use slices (as for lists): `df.iloc[0:2]`.

####  Selection on rows and columns
Of course, both types of selection (row and column) can be combined:
```
df.loc["mouse", "Pau"] 2 33
df.loc[["monkey", "mouse"], ['Nantes ', 'Lyon ']]
```
Note that as soon as you want to make a selection on lines, you have to use loc (or iloc if you use indices).

####  Selection by condition
Now select all rows for which the number of employees in Pau is greater than 15: 
`df[ df["Pau"]>15 ] `
From this selection, we wish to keep only the values for Lyon:
`df[ df["Pau"]>15 ][" Lyon"]`

You can also combine several conditions with & for the and operator:
`df[ (df["Pau "] >15) & (df["Lyon "]>25) ]`
and | for the or operator:
`df[ (df["Pau "] >15) | (df["Lyon "]>25) ]`